name: 'Pull Request auto-assign'
description: 'Automatically add Assignees to a PR'
inputs:
  repo-token:
    description: 'Github token for the repository'
    default: ${{ github.token }}
    required: false
  assignee:
    description: 'Github username the PR should be assigned to'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
