name: 'Pull Request auto-assign'
description: 'Automatically add Assignees to a PR'
inputs:
  repo-token:
    description: 'Github token for the repository'
    default: ${{ github.token }}
    required: false
  assignee:
    description: 'Username of the assignee'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
